---
# Juniper Spine-Leaf Datacenter Fabric Inventory

all:
  children:
    dc_fabric:
      children:
        spines:
          hosts:
            dc1-spine-01:
              ansible_host: 10.255.0.1
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-spine-02:
              ansible_host: 10.255.0.2
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-spine-03:
              ansible_host: 10.255.0.3
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-spine-04:
              ansible_host: 10.255.0.4
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin

        leaves:
          hosts:
            dc1-leaf-001:
              ansible_host: 10.255.1.1
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-002:
              ansible_host: 10.255.1.2
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-003:
              ansible_host: 10.255.1.3
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-004:
              ansible_host: 10.255.1.4
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-005:
              ansible_host: 10.255.1.5
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-006:
              ansible_host: 10.255.1.6
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-007:
              ansible_host: 10.255.1.7
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-008:
              ansible_host: 10.255.1.8
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-009:
              ansible_host: 10.255.1.9
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-010:
              ansible_host: 10.255.1.10
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-011:
              ansible_host: 10.255.1.11
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-012:
              ansible_host: 10.255.1.12
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-013:
              ansible_host: 10.255.1.13
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-014:
              ansible_host: 10.255.1.14
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-015:
              ansible_host: 10.255.1.15
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-016:
              ansible_host: 10.255.1.16
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-017:
              ansible_host: 10.255.1.17
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-018:
              ansible_host: 10.255.1.18
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-019:
              ansible_host: 10.255.1.19
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-020:
              ansible_host: 10.255.1.20
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-021:
              ansible_host: 10.255.1.21
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-022:
              ansible_host: 10.255.1.22
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-023:
              ansible_host: 10.255.1.23
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-024:
              ansible_host: 10.255.1.24
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-025:
              ansible_host: 10.255.1.25
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-026:
              ansible_host: 10.255.1.26
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-027:
              ansible_host: 10.255.1.27
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-028:
              ansible_host: 10.255.1.28
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-029:
              ansible_host: 10.255.1.29
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-030:
              ansible_host: 10.255.1.30
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-031:
              ansible_host: 10.255.1.31
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-032:
              ansible_host: 10.255.1.32
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-033:
              ansible_host: 10.255.1.33
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-034:
              ansible_host: 10.255.1.34
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-035:
              ansible_host: 10.255.1.35
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-036:
              ansible_host: 10.255.1.36
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-037:
              ansible_host: 10.255.1.37
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-038:
              ansible_host: 10.255.1.38
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-039:
              ansible_host: 10.255.1.39
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-040:
              ansible_host: 10.255.1.40
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-041:
              ansible_host: 10.255.1.41
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-042:
              ansible_host: 10.255.1.42
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-043:
              ansible_host: 10.255.1.43
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-044:
              ansible_host: 10.255.1.44
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-045:
              ansible_host: 10.255.1.45
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-046:
              ansible_host: 10.255.1.46
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-047:
              ansible_host: 10.255.1.47
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-048:
              ansible_host: 10.255.1.48
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-049:
              ansible_host: 10.255.1.49
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-050:
              ansible_host: 10.255.1.50
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-051:
              ansible_host: 10.255.1.51
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-052:
              ansible_host: 10.255.1.52
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-053:
              ansible_host: 10.255.1.53
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-054:
              ansible_host: 10.255.1.54
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-055:
              ansible_host: 10.255.1.55
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-056:
              ansible_host: 10.255.1.56
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-057:
              ansible_host: 10.255.1.57
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-058:
              ansible_host: 10.255.1.58
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-059:
              ansible_host: 10.255.1.59
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
            dc1-leaf-060:
              ansible_host: 10.255.1.60
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_port: 830
              ansible_user: admin
